---
- hosts: 
  vars:
  become: true
  remote_user: user-ansible
  tasks:
    - name: Install prerequisites
      apt: update_cache=yes state=latest force_apt_get=yes

    - name: Installation de Virtualbox 
      apt: name={{ item }} update_cache=yes state=latest
      loop: ['virtualbox-6.1']

    - name: Création du répertoire VMs
      file:
        path: /home/user/VirtualBox VMs/
        state: directory
        owner: nobody
        group: nogroup
        mode: 0777

    - name: Installation des dépendances de GNS3
      apt: name={{ item }} update_cache=yes state=latest
      loop: ['python-pip', 'python3-pip','python3-pyqt5', 'python3-pyqt5.qtsvg' ,'python3-pyqt5.qtwebsockets','qemu','qemu-kvm','qemu-utils','libvirt-clients','libvirt-daemon-system','virtinst','wireshark', 'xtightvncviewer', 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']

    - name: Installation gns3-server via pip 
      pip: 
        name: gns3-server
        executable: pip3

    - name: Installation gns3-gui via pip 
      pip:
        name: gns3-gui
        executable: pip3

    - name: Téléchargement de la VM GNS3 
      get_url: 
        url: http://www.dmz.tld/GNS3.VM.VirtualBox.2.2.8.zip
        dest: /srv/logiciels/

    - name: Unzip de la VM GNS3
      unarchive:
        src: /srv/logiciels/GNS3.VM.VirtualBox.2.2.8.zip
        dest: /home/user/VirtualBox VMs/
        remote_src: yes
  
    - name: Changement de propriétaire de la VM GNS3
      file:
        path: /home/user/VirtualBox VMs/GNS3 VM.ova
        owner: nobody
        group: nogroup
        mode: '0777'
